### ISSUE TITLE
ember-outdated fails on newer versions of ember-cli without bower.json

### ISSUE THREAD

**Issue by amk221** [dstaley/ember-outdated#2]
Here's the output from `ember-outdated --debug`

https://pastebin.com/851MuL8U

**Comment by nerdyworm** [comment]
Same issue for me.

```
❯ node --version
v7.9.0
❯ npm --version
4.2.0
```

**Comment by dstaley** [comment]
This is due to the removal of bower.json from newer versions of ember-cli.

**Comment by pauldoerwald** [comment]
It's pretty hacky, but I was able to get ember-outdated to run by editing (according to my path /usr/local/bin/ember-outdated) and removing all the blocks that refer to bower. 

    *** lib/ember-outdated.js 2017-07-13 17:22:19.000000000 -0300
    --- /usr/local/bin/ember-outdated 2017-07-13 17:27:16.000000000 -0300
    ***************
    *** 1,7 ****
      #! /usr/bin/env node
      
      var _npm = require('./_npm');
    - var _bower = require('./_bower');
      var rsvp = require('rsvp');
      var Table = require('cli-table');
      var _ = require('lodash');
    --- 1,6 ----
    ***************
    *** 62,91 ****
      }
      
      var promises = {
    -   'bower.json': _bower.getBowerDependencies(),
        'package.json': _npm.getPackageDependencies()
      };
      
      if (cli.debug) {
    -   promises['ember-cli-bower.json'] = github.getLatestRelease()
    -     .then(function(tag) {
    -       return github.getBowerJson(tag);
    -     });
    - 
        promises['ember-cli-package.json'] = github.getLatestRelease()
          .then(function(tag) {
            return github.getPackageJson(tag);
          });
      
        promises['debug-npm'] = _npm.debugNpm();
    -   promises['debug-bower'] = _bower.debugBower();
      }
      
      rsvp.hash(promises).then(function(results) {
        if (cli.debug) {
          console.log(JSON.stringify(results)); // eslint-disable-line no-console
        } else {
    !     var packages = results['package.json'].concat(results['bower.json']);
          packages = _(packages)
            .filter(util.differentFromCli)
            .filter(util.notSatisfiedBySemver)
    --- 61,83 ----
      }
      
      var promises = {
        'package.json': _npm.getPackageDependencies()
      };
      
      if (cli.debug) {
        promises['ember-cli-package.json'] = github.getLatestRelease()
          .then(function(tag) {
            return github.getPackageJson(tag);
          });
      
        promises['debug-npm'] = _npm.debugNpm();
      }
      
      rsvp.hash(promises).then(function(results) {
        if (cli.debug) {
          console.log(JSON.stringify(results)); // eslint-disable-line no-console
        } else {
    !     var packages = results['package.json']
          packages = _(packages)
            .filter(util.differentFromCli)
            .filter(util.notSatisfiedBySemver)

**Comment by pauldoerwald** [comment]
An alternative, which I'm finding works better than with my hack above is to use the tools that come with npm/yarn:

    yarn outdated

or

    npm outdated

**Comment by dstaley** [comment]
ember-outdated is actually powered by the output of `npm outdated` so
that's a great alternative!
